words = ["abrasivo", "abrupto", "ausente", "absorbido", "absorbente", "abstraído", "absurdo",
 "abundante", "abusivo", "aceptar", "aceptable", "accesible", "accidental", "cuenta", "preciso", 
"realizador", "ácido", "acústico", "acústica", "acre", 
"actuar", "acción", "actividad", "actor", "en realidad", "adaptable", "añadir", "adicto", 
"adorable", "enojo", "ángulo", "enojado", "animal", "animado", "anunciar", "molestar", 
"fastidiado", "molesto", "respuesta", "hormigas", "ansioso", "apático", "disculparse", 
"aparato", "indumentaria", "aparecer", "aplaudir", "aparato", "apreciar", "aprobación", 
"aprobar", "acuático", "arco", "discutir", "argumento", "aritmética", "brazo", "ejército",
"aromático", "arreglar", "arrestar", "llegar", "arrogante", "arte", "avergonzado",
"preguntar", "aspirante", "variado", "asombroso", "adjuntar", "atacar", "intentar", 
"atender", "atraer", "atracción", "atractivo", "tía", "auspicioso", "autoridad", 
"automático", "disponible", "promedio", "evitar", "despierto", "consciente",
"impresionante", "horrible", "axiomático", "bebés", "bebé", "espalda", "malo", 
"insignia", "campanas", "pertenecer", "beneficioso", "doblado", "baya", "mejor",  
"cumpleaños",  "ojos azules", "sonrojarse", "sonrojarse", "tabla",  "barco", "hervir",
"hirviendo", "perno", "bomba", "hueso", "libro", "libros", "grosero", "bota", "frontera",
"aburrir", "aburrido", "aburrido", "prestado", "botella", "rebote", "saltarín", "límite", 
"ilimitado", "arco", "caja", "niño", "sesudo", "freno", "rama", "descarado", "latón", 
"valiente", "musculoso", "quebradizo", "aliento", "respira", "brisa", "ladrillo", 
"puente", "breve", "brillante", "ancho", "roto", "hermano", "marrón", "moratón", 
"cepillo", "burbuja", "cubo", "edificio", "bombilla", "bulto", "accidentado",  
"cuidado", "cuidadoso", "descuidado", "cuidado", "carpintero", "carruaje", "llevar", 
"coches", "carro", "tallar", "fundir", "gato", "gatos", "ganado", "causa", "cauteloso", 
"cueva", "incesante", "apio", "bodega", "cementerio", "centavo", "cierto", "tiza", 
"desafío", "oportunidad", "cambio", "cambiante", "canal", "carga", "encantador", 
"persecución", "barato", "trampa", "cheque", "tela", "nublado", "trébol", "club", 
"torpe", "desordenado", "entrenador", "carbón", "costa", "abrigo", "telaraña", 
"coherente", "bobina", "frío", "cuello", "recoger", "color", "colorido", "colosal",
"color", "peine", "combativo", "cómodo", "mando", "comité", "común", "comunicar", 
"empresa", "comparar", "comparación", "competir", "competición", "quejarse", "completo", 
"complejo", "concentrado", "preocupación", "preocupado", "condenado", "condición", 
"confesar", "confundir", "confuso", "conectar", "conexión", "consciente", "considerar", 
"consistir", "contener", "continuar", "controlar", "arrullar", "cocinar", "enfriar", 
"cooperar", "coordinar", "cobre", "copiar", "maíz", "corregir", "toser", "contar", 
"country", "crédito", "espeluznante", "cuna", "crimen", "ladrón", "torcido", "cruz",
"cuervo", "multitud", "abarrotado", "corona", "cruel", "aplastar", "llorar", 
"cachorro", "adorable", "culto", "engorroso", "taza", "cura", "curioso", "rizo", 
"rizado", "corriente", "cortina", "curva", "curvado", "cojín", "corte", "lindo",
"ciclo", "cínico", "papá", "diario", "presa", "muerte", "gallardo", "deuda", 
"decadencia", "engañar", "decidir", "decisión", "decisivo", "decorar", "decoroso",
"profundo", "profundamente", "ciervo","derrotado", "defectuoso", "desafiante",
"degre"]



